export const dataMenu = [
    {
        id: 0,
        link: "#",
        image: "img/home_FILL0_wght300_GRAD0_opsz24.svg",
        alt: "Overview",
        text: "Overview",
    },
    {
        id: 1,
        link: "#",
        image: "img/group_FILL0_wght300_GRAD0_opsz24.svg",
        alt: "Patients",
        text: "Patients",
    },
    {
        id: 2,
        link: "#",
        image: "img/calendar_today_FILL0_wght300_GRAD0_opsz24.svg",
        alt: "Schedule",
        text: "Schedule",
    },
    {
        id: 3,
        link: "#",
        image: "img/chat_bubble_FILL0_wght300_GRAD0_opsz24.svg",
        alt: "Message",
        text: "Message",
    },
    {
        id: 4,
        link: "#",
        image: "img/credit_card_FILL0_wght300_GRAD0_opsz24.svg",
        alt: "Transactions",
        text: "Transactions",
    },
];

export const patiensList = [
    {
        id: 0,
        image: "img/Layer 8.png",
        title: "Emily Williams",
        sex: "Female",
        age: "18",
    },
    {
        id: 1,
        image: "img/Layer 1.png",
        title: "Ryan Johnson",
        sex: "Male",
        age: "45",
    },
    {
        id: 2,
        image: "img/Layer 3.png",
        title: "Brandon Mitchell",
        sex: "Male",
        age: "36",
    },
    {
        id: 3,
        image: "img/Layer 2.png",
        title: "Jessica Taylor",
        sex: "Female",
        age: "28",
    },
    {
        id: 4,
        image: "img/Layer 6.png",
        title: "Samantha Johnson",
        sex: "Female",
        age: "56",
    },
    {
        id: 5,
        image: "img/Layer 12.png",
        title: "Ashley Martinez",
        sex: "Female",
        age: "54",
    },
    {
        id: 6,
        image: "img/Layer 10.png",
        title: "Olivia Brown",
        sex: "Female",
        age: "32",
    },
    {
        id: 7,
        image: "img/Layer 9.png",
        title: "Tyler Davis",
        sex: "Male",
        age: "19",
    },
    {
        id: 8,
        image: "img/Layer 4.png",
        title: "Kevin Anderson",
        sex: "Male",
        age: "30",
    },
    {
        id: 9,
        image: "img/Layer 5.png",
        title: "Dylan Thompson",
        sex: "Male",
        age: "36",
    },
    {
        id: 10,
        image: "img/Layer 7.png",
        title: "Nathan Evans",
        sex: "Male",
        age: "58",
    },
    {
        id: 11,
        image: "img/pexels-photo-1222271.png",
        title: "Mike Nolan",
        sex: "Male",
        age: "31",
    },
    {
        id: 12,
        image: "img/Layer 8.png",
        title: "Emily Williams",
        sex: "Female",
        age: "18",
    },
    {
        id: 13,
        image: "img/Layer 1.png",
        title: "Ryan Johnson",
        sex: "Male",
        age: "45",
    },
    {
        id: 14,
        image: "img/Layer 3.png",
        title: "Brandon Mitchell",
        sex: "Male",
        age: "36",
    },
    {
        id: 15,
        image: "img/Layer 2.png",
        title: "Jessica Taylor",
        sex: "Female",
        age: "28",
    },
    {
        id: 16,
        image: "img/Layer 6.png",
        title: "Samantha Johnson",
        sex: "Female",
        age: "56",
    },
    {
        id: 17,
        image: "img/Layer 12.png",
        title: "Ashley Martinez",
        sex: "Female",
        age: "54",
    },
    {
        id: 18,
        image: "img/Layer 10.png",
        title: "Olivia Brown",
        sex: "Female",
        age: "32",
    },
    {
        id: 19,
        image: "img/Layer 9.png",
        title: "Tyler Davis",
        sex: "Male",
        age: "19",
    },
    {
        id: 20,
        image: "img/Layer 4.png",
        title: "Kevin Anderson",
        sex: "Male",
        age: "30",
    },
    {
        id: 21,
        image: "img/Layer 5.png",
        title: "Dylan Thompson",
        sex: "Male",
        age: "36",
    },
    {
        id: 22,
        image: "img/Layer 7.png",
        title: "Nathan Evans",
        sex: "Male",
        age: "58",
    },
    {
        id: 23,
        image: "img/pexels-photo-1222271.png",
        title: "Mike Nolan",
        sex: "Male",
        age: "31",
    },

];
